name: 'OpenAPI Lint Action'
description: 'Use OpenAPI Linter in GitHub Actions'
author: 'nwestfall'
inputs:
  github_token:
    required: true
    description: 'GitHub Personal Access Token'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'blue'